project_id = "eyvcrvqpxlldxyrfwjpn"

[api]
enabled = true

[functions.send-order-email]
verify_jwt = false

[functions.send-status-update-email]
verify_jwt = false

[functions.send-admin-notification]
verify_jwt = false

[functions.send-payment-confirmed-email]
verify_jwt = false

[functions.send-telegram-notification]
verify_jwt = false

[functions.submit-contact]
verify_jwt = false

[functions.create-pix-payment]
verify_jwt = false

[functions.check-payment-status]
verify_jwt = false

[functions.create-checkout-link]
verify_jwt = false

[functions.mercadopago-webhook]
verify_jwt = false

[functions.create-order]
verify_jwt = false

[functions.admin-get-pedidos]
verify_jwt = false

[functions.admin-get-clientes]
verify_jwt = false

[functions.admin-get-metrics]
verify_jwt = false

[functions.admin-get-sales]
verify_jwt = false

[functions.sitemap]
verify_jwt = false
