project_id = "eyvcrvqpxlldxyrfwjpn"

[api]
enabled = true

[functions.send-order-email]
verify_jwt = false

[functions.send-status-update-email]
verify_jwt = false

[functions.create-pix-payment]
verify_jwt = false

[functions.check-payment-status]
verify_jwt = false

[functions.create-checkout-link]
verify_jwt = false

[functions.mercadopago-webhook]
verify_jwt = false

[functions.create-checkout-link]
verify_jwt = false
